NureStatistic/src/NureStatistic.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace NureStatistic.Web.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ViewResult Index()
        {
            return View();
        }

        [HttpGet]
        [ResponseCache(Duration = 300)]
        public PartialViewResult IndexContent()
        {
            return PartialView();
        }
    }
}

NureStatistic/src/NureStatistic.Web/Controllers/StatisticController.cs
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using NureStatistic.BLL.Interfaces;

namespace NureStatistic.Web.Controllers
{
    public class StatisticController : Controller
    {
        private readonly IStatisticService _statisticService;

        public StatisticController(IStatisticService statisticService)
        {
            _statisticService = statisticService;
        }

        [HttpGet]
        public async Task<JsonResult> GetTeacherStatistic(string teacherId, DateTime from, DateTime to)
        {
            SetDefaultInterval(ref from, ref to);

            var result = await _statisticService.GetTeacherStatisticAsync(teacherId, from, to);

            return Json(result);
        }

        [HttpGet]
        public async Task<JsonResult> GetGroupStatistic(string groupId, DateTime from, DateTime to)
        {
            SetDefaultInterval(ref from, ref to);

            var result = await _statisticService.GetGroupStatisticAsync(groupId, from, to);

            return Json(result);
        }

        private void SetDefaultInterval(ref DateTime from, ref DateTime to)
        {
            if (from == default(DateTime) && to == default(DateTime))
            {
                from = DateTime.UtcNow;
                to = from.AddDays(14);
            }
            else if (from != default(DateTime) && to == default(DateTime))
            {
                to = from.AddDays(14);
            }
        }
    }
}

NureStatistic/src/NureStatistic.Web/Controllers/StructureController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NureStatistic.BLL.Interfaces;
using NureStatistic.Web.Attributes;

namespace NureStatistic.Web.Controllers
{
    [AsyncRequest]
    [ResponseCache(Duration = 300)]
    public class StructureController : Controller
    {
        private readonly IStructureService _structureService;

        public StructureController(IStructureService structureService)
        {
            _structureService = structureService;
        }

        [HttpGet]
        public async Task<PartialViewResult> Teacher()
        {
            var university = await _structureService.GetTeacherStructure();

            return PartialView(university);
        }

        [HttpGet]
        public async Task<PartialViewResult> Group()
        {
            var university = await _structureService.GetGroupStructure();

            return PartialView(university);
        }

        [HttpGet]
        public async Task<PartialViewResult> Auditory()
        {
            var university = await _structureService.GetAuditoryStructure();

            return PartialView(university);
        }
    }
}

NureStatistic/src/NureStatistic.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Knure TSTM";
}

@section submenu
{
    <div class="nav-wrapper container search-block">
        <form>
            <div class="input-field">
                <input id="search" type="search" required>
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
            </div>
        </form>
    </div>
    <div class="nav-content container">
        <ul class="tabs tabs-transparent" data-is-submenu-buttons-list="true" >
            <li class="tab"><a asp-controller="Home" asp-action="IndexContent" class="active">Home</a></li>
            <li class="tab"><a asp-controller="Structure" asp-action="Teacher">Teacher</a></li>
            <li class="tab"><a asp-controller="Structure" asp-action="Group">Group</a></li>
            <li class="tab"><a asp-controller="Structure" asp-action="Auditory">Auditory</a></li>
        </ul>
    </div>
}

<div data-is-content-wrapper="true"></div>

@section scripts {       
    <environment names="Development">
      <script src="~/js/cookiemanager.js"></script>
      <script src="~/js/index.js"></script>
    </environment>
    <environment names="Staging,Production">
      <script src="~/js/cookiemanager.min.js"></script>
      <script src="~/js/index.min.js"></script>
    </environment>
}

NureStatistic/src/NureStatistic.Web/Views/Home/IndexContent.cshtml
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center teal-text text-lighten-2">Kharkiv National University Of Radioelectronics</h1>
            <div class="row center">
                <a href="http://nure.ua/" class="btn-large waves-effect waves-light teal lighten-1">Official Site</a>
            </div>
            <br><br>
        </div>
    </div>
    <div class="parallax"><img src="images/nure1.jpg" alt="Nure Picture"></div>
</div>

<div class="container">
    <div class="section">
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
                    <h5 class="center">Short response time</h5>
                    <p class="light">We have used cutting edge technologies for creating high-performance web application, so that you can get helpful information about timetable with shortest delay to manage time more effectively.</p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">group</i></h2>
                    <h5 class="center">User Experience Focused</h5>
                    <p class="light">By utilizing elements and principles of Material Design, we were able to create a web site that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
                    <h5 class="center">Easy to work with</h5>
                    <p class="light">We have provided obvious user interface to help new users get started. You have opportunity to get any provided us information in a few clicks or typed words.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h3 class="header col s12 light">Teachers And Students Time Management</h3>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="images/nure2.jpg" alt="Nure Picture"></div>
</div>
<div class="container">
    <div class="section">
        <div class="row">
            <div class="col s12 center">
                <h4>Application Description</h4>
                <p class="left-align light">
                    The given application has been developed to provide facilities of getting statistic, helpful information, convenient way to communicate between student and teacher
                    (e.g. assign meeting apart from official timetable) by using cist.nure.ua Native API and own database.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h5 class="header col s12 light">Get statistic about your group, teacher, lecture hall that you attend as tables, graphics or charts</h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="images/nure3.jpg" alt="Nure Picture"></div>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/js/materialize.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script type="text/javascript" src="~/js/materialize.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

NureStatistic/src/NureStatistic.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <environment names="Development">
        <link type="text/css" rel="stylesheet" href="~/css/materialize.css" media="screen,projection" />
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment names="Staging,Production">
        <link type="text/css" rel="stylesheet" href="~/css/materialize.min.css" media="screen,projection" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("styles", required: false)
</head>
<body>
    <nav class="nav-extended white" role="navigation">
        <div class="nav-wrapper container">
            <a class="brand-logo" asp-controller="Home" asp-action="Index">KNURE</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="#">Login</a></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
                <li><a href="#">Login</a></li>
            </ul>
        </div>
        
        @RenderSection("submenu", required: false)

    </nav>

    @RenderBody()
    
    <footer class="page-footer teal">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">University Bio</h5>
                    <p class="grey-text text-lighten-4">Kharkiv National University of Radioelectronics (KNURE) is a higher education institution of the highest level of accreditation in Ukraine. It is one of the oldest Universities of Technologies in Ukraine with over 12000 students and 30 scientific centers.</p>

                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Contact Us</h5>
                    <ul>
                        <li><span class="white-text">Developer's email: oleksandr.chyzh@nure.ua</span></li>
                    </ul>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li><a class="white-text" href="http://nure.ua/">Knure official site</a></li>
                        <li><a class="white-text" href="http://cist.nure.ua/">Knure timetable</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Made by <span class="brown-text text-lighten-3">Oleksandr Chyzh</span>
            </div>
        </div>
    </footer>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/js/materialize.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script type="text/javascript" src="~/js/materialize.min.js"></script>
</environment>

@RenderSection("scripts", required: false)
</body>
</html>

NureStatistic/src/NureStatistic.Web/Views/Structure/Auditory.cshtml
@using NureStatistic.BLL.Dto;
@model UniversityDto

<div class="container">
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header" title="@Model.FullName">@Model.ShortName<i class="material-icons">send</i></div>
      <div class="collapsible-body">
        <ul class="collapsible" data-collapsible="expandable">
          @foreach (var building in Model.Buildings)
          {
              <li>
                <div class="collapsible-header" title="@building.FullName">@building.ShortName<i class="material-icons">send</i></div>
                <div class="collapsible-body">
                  <ul class="collection">
                    @foreach (var auditory in building.Auditories)
                    {
                      var floor = auditory.Floor == null ? "undefined" : auditory.Floor.ToString();
                        <li class="collection-item" title="Floor: @floor" data-auditory-id="@auditory.Id">@auditory.ShortName</li>
                    }
                  </ul>
                </div>
              </li>
          }
        </ul>
      </div>
  </ul>
</div>
<script>
  $(document).ready(function () {
    $('.collapsible').collapsible();
  });
</script>

NureStatistic/src/NureStatistic.Web/Views/Structure/Group.cshtml
@using NureStatistic.BLL.Dto;
@model UniversityDto

<div class="container">
  <div class="row">
    <div class="input-field col m6">
      <i class="material-icons prefix">today</i>
      <input id="date-from" type="date" class="datepicker" data-is-date-from="true">
      <label for="date-from">From</label>
    </div>

    <div class="input-field col m6">
      <i class="material-icons prefix">today</i>
      <input id="date-to" type="date" class="datepicker" data-is-date-to="true">
      <label for="date-to">To</label>
    </div>
  </div>

  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header" title="@Model.ShortName">@Model.FullName<i class="material-icons">send</i>
      </div>
      <div class="collapsible-body">
        <ul class="collapsible" data-collapsible="expandable">
          @foreach (var faculty in Model.Faculties)
          {
            <li>
              <div class="collapsible-header" title="@faculty.ShortName">@faculty.FullName<i class="material-icons">send</i>
              </div>
              <div class="collapsible-body">
                <ul class="collapsible" data-collapsible="expandable">
                  @foreach (var direction in faculty.Directions)
                  {
                    <li>
                      <div class="collapsible-header" title="@direction.ShortName">@direction.FullName<i class="material-icons">send</i>
                      </div>
                      <div class="collapsible-body">
                        @if (direction.Groups != null)
                        {
                          <ul class="collection">
                            @foreach (var group in direction.Groups)
                            {
                              <li class="collection-item"><a href="" data-group-id="@group.Id">@group.Name</a></li>
                            }
                          </ul>
                        }
                      </div>
                    </li>
                  }
                </ul>
              </div>
            </li>
          }
        </ul>
      </div>
    </li>
  </ul>
  
  <div id="daily-occupations-container"></div>
  <div id="event-type-counts-container"></div>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="~/js/group.js"></script>

NureStatistic/src/NureStatistic.Web/Views/Structure/Teacher.cshtml
@using NureStatistic.BLL.Dto;
@model UniversityDto

<div class="container">
  <div class="row">
    <div class="input-field col m6">
      <i class="material-icons prefix">today</i>
      <input id="date-from" type="date" class="datepicker" data-is-date-from="true">
      <label for="date-from">From</label>
    </div>

    <div class="input-field col m6">
      <i class="material-icons prefix">today</i>
      <input id="date-to" type="date" class="datepicker" data-is-date-to="true">
      <label for="date-to">To</label>
    </div>
  </div>

  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header" title="@Model.FullName">@Model.ShortName<i class="material-icons">send</i>
      </div>
      <div class="collapsible-body">
        <ul class="collapsible" data-collapsible="expandable">
          @foreach (var faculty in Model.Faculties)
          {
            <li>
              <div class="collapsible-header" title="@faculty.FullName">@faculty.ShortName<i class="material-icons">send</i>
              </div>
              <div class="collapsible-body">
                <ul class="collapsible" data-collapsible="expandable">
                  @foreach (var department in faculty.Departments)
                  {
                    <li>
                      <div class="collapsible-header" title="@department.FullName">@department.ShortName<i class="material-icons">send</i>
                      </div>
                      <div class="collapsible-body">
                        <ul class="collection">
                          @foreach (var teacher in department.Teachers)
                          {
                            <li class="collection-item" title="@teacher.FullName"><a href="" data-teacher-id="@teacher.Id">@teacher.ShortName</a></li>
                          }
                        </ul>
                      </div>
                    </li>
                  }
                </ul>
              </div>
            </li>
          }
        </ul>
      </div>
    </li>
  </ul>

  <div id="daily-occupations-container"></div>
  <div id="event-type-counts-container"></div>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script src="~/js/teacher.js"></script>